"""add scoring tables

Revision ID: a1c2d3e4f5a6
Revises: f3aab5f3fa96
Create Date: 2026-07-28 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c2d3e4f5a6'
down_revision: Union[str, Sequence[str], None] = 'f3aab5f3fa96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='scanstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('photos_total', sa.Integer(), nullable=False),
    sa.Column('photos_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_scores',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('sharpness', sa.Float(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=False),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('cluster_key', sa.String(), nullable=True),
    sa.Column('local_quality_score', sa.Float(), nullable=True),
    sa.Column('suggested_status', sa.Enum('FAVORITE', 'ALBUM_WORTHY', 'REJECTED', name='ratingstatus', native_enum=False, length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_scores')
    op.drop_table('scoring_runs')
    # ### end Alembic commands ###
